@startuml style
''Style config
hide circle
skinparam classFontStyle bold
skinparam groupInheritance 2
set separator ::
skinparam classAttributeIconSize 0
    
class Model::Player{
    {field} credits: int
    {field} crew: int[3]
    {field} distance: int
    {field} spaceship: SpaceShip
}

''Class declaration
interface Model::Components::iSC as "Starship Component"{
    --methods--
    {method} +getConnectors() : ConnectorType[4]
    {method} +getType() : ComponentType
}

abstract Model::Components::SC as "Base Component" {
    {field} -connectors : ConnectorType
    {field} -type : ComponentType
    {field} -rotation: ComponentRotation
    --methods--
    {method} +getConnectors() : int[4]
    {method} +getType() : ComponentType
}

class Model::Components::CBC as "Cabin Component" {
}

class Model::Components::ACC as "Alien Cabin Component" {
}

class Model::Components::EC as "Engine Component" {
}

class Model::Components::BEC as "Double Engine Component" {
}

class Model::Components::ASC as "Life Support Component" {
}

class Model::Components::CNC as "Cannon Component"{
}

class Model::Components::DAC as "Double Cannon Component" {
}

class Model::Components::STC as "Storage Component" {
}

class Model::Components::BC as "Battery Component" {
}

class Model::Components::SHC as "Shield Component" {
}

''Il mucchio di celle
interface Model::iCommonBoard{
    ---methods---
    {method} pull_component(): Starship Component
    {method} discard_component(Starship Component a): void
    {method} pull_discarded(): Starship Component
}

class Model::CommonBoard{
    {field} covered_components: Queue<Starship Component>
    {field} uncovered_components: ArrayList<Starship Component>
    --methods--
    {field} covered_components: Queue<Starship Component>
    {field} uncovered_components: ArrayList<Starship Component>
}

interface Model::iSpaceShip{
    --methods--
    {method} verify(): void
    {method} add_component(Starship Component comp, usize index)
}

''Relations between classes
Model::Components::iSC^----Model::Components::SC
Model::Components::SC^----Model::Components::CBC
Model::Components::CBC^----Model::Components::ACC
Model::Components::SC^----Model::Components::EC
Model::Components::SC^----Model::Components::BEC
Model::Components::SC^----Model::Components::ASC
Model::Components::SC^----Model::Components::CNC
Model::Components::SC^----Model::Components::DAC
Model::Components::SC^----Model::Components::BC
Model::Components::SC^----Model::Components::STC
Model::Components::SC^----Model::Components::SHC


Model::iCommonBoard ^--- Model::CommonBoard
Model::Components::SC <--* "0..n covered_components" Model::CommonBoard

@enduml