@startuml uml_complete
hide circle
skinparam classFontStyle bold
skinparam groupInheritance 1
set separator ::
skinparam classAttributeIconSize 12

package Model {

    package Cards {

        package State {

            abstract CardState {
                {field} [protected] state : VoyageState
                {method} + init(ClientModelState) : void
                {method} + [abstract] validate() : void
                {method} + [abstract] getClientCardState() : ClientCardState
                {method} + [abstract] getNext() : CardState
                {method} + transition() : void
                {method} + setNewShipCentre(Player, ShipCoords) : void
                {method} + turnOn(Player, ShipCoords, ShipCoords) : void
                {method} + removeCrew(Player, ShipCoords): void
                {method} + moveCargo(Player, ShipmentType, ShipCoords, ShipCoords) : void
                {method} + takeCargo(Player, ShipmentType, ShipCoords) : void
                {method} + discardCargo(Player, ShipmentType, ShipCoords) : void
                {method} + selectLanding(Player, int) : void
                {method} + progressTurn(Player) : void
                {method} + setTakeReward(Player, boolean) : void
                {method} + connect(Player) : void
                {method} + disconnect(Player) : void
            }

            CardState^--AbandonedShipAnnounceState
            class AbandonedShipAnnounceState {
                {field} [final] card : AbandonedShipCard
                {field} [final] list : List<Player>
                {field} responded : boolean
                {field} id : int
                {method} + init(ClientModelState) : void
                {method} + validate(ServerMessage) : void
                {method} + getClientCardState() : ClientCardState
                {method} [protected] getNext() : CardState
                {method} + selectLanding(Player, int) : void
                {method} + disconnect(Player) : void
            }

            CardState^--AbandonedShipRewardState
            class AbandonedShipRewardState {
                {field} [final] card : AbandonedShipCard
                {field} [final] list : List<Player>
                {field} coords : List<ShipCoords>
                {field} responded : boolean
                {method} + init(ClientModelState) : void
                {method} + validate(ServerMessage) : void
                {method} + getClientCardState() : ClientCardState
                {method} [protected] getNext() : CardState
                {method} + removeCrew(Player, ShipCoords) : void
                {method} + disconnect(Player) : void
            }

            CardState^--AbandonedStationAnnounceState
            class AbandonedStationAnnounceState {
                {field} [final] card : AbandonedStationCard
                {field} [final] list : List<Player>
                {field} responded : boolean
                {field} id : int
                {method} + init(ClientModelState) : void
                {method} + validate(ServerMessage) : void
                {method} + getClientCardState() : ClientCardState
                {method} [protected] getNext() : CardState
                {method} + selectLanding(Player, int) : void
                {method} + disconnect(Player) : void
            }

            CardState^--AbandonedStationRewardState
            class AbandonedStationRewardState {
                {field} [final] card : AbandonedStationCard
                {field} [final] list : List<Player>
                {field} responded : boolean
                {method} + init(ClientModelState) : void
                {method} + validate(ServerMessage) : void
                {method} + getClientCardState() : ClientCardState
                {method} [protected] getNext() : CardState
                {method} + takeCargo(Player, ShipmentType, ShipCoords) : void
                {method} + moveCargo(Player, ShipmentType, ShipCoords, ShipCoords) : void
                {method} + discardCargo(Player, ShipmentType, ShipCoords) : void
                {method} + progressTurn(Player) : void
                {method} + disconnect(Player) : void

            }

            CardState^--CombatZoneAnnounceState
            class CombatZoneAnnounceState {
                {field} [final] card_id : int
                {field} [final] sections : List<CombatZoneSection>
                {field} [final] shots : ProjectileArray
                {field} awaiting : List<Player>
                {field} target : Player
                {method} + init(ClientModelState) : void
                {method} + validate(ServerMessage) : void
                {method} + getClientCardState() : ClientCardState
                {method} [protected] getNext() : CardState
                {method} + turnOn(Player, ShipCoords, ShipCoords) : void
                {method} + progressTurn(Player) : void
                {method} + disconnect(Player) : void
            }

            CardState^--CombatZoneNewCabinState
            class CombatZoneNewCabinState {
                {field} [final] card_id : int
                {field} [final] sections : List<CombatZoneSection>
                {field} [final] shots : ProjectileArray
                {field} target : Player
                {method} + init(ClientModelState) : void
                {method} + validate(ServerMessage) : void
                {method} + getClientCardState() : ClientCardState
                {method} [protected] getNext() : CardState
                {method} + setNewShipCentre(Player, ShipCoords) : void
                {method} + disconnect(Player) : void
            }

            CardState^--CombatZonePenaltyState
            class CombatZonePenaltyState {
                {field} [final] card_id : int
                {field} [final] sections : List<CombatZoneSection>
                {field} [final] shots : ProjectileArray
                {field} target : Player
                {field} [final] required : int[]
                {field} responded : boolean
                {field} coords : List<ShipCoords>
                {method} + init(ClientModelState) : void
                {method} + validate(ServerMessage) : void
                {method} + getClientCardState() : ClientCardState
                {method} [protected] getNext() : CardState
                {method} + turnOn(Player, ShipCoords, ShipCoords) : void
                {method} + progressTurn(Player) : void
                {method} + removeCrew(Player, ShipCoords) : void
                {method} + discardCargo(Player, ShipmentType, ShipCoords) : void
                {method} + disconnect(Player) : void
            }

            CardState^--EpidemicState
            class EpidemicState {
                {field} [final] card : EpidemicCard
                {field} [final] awaiting : List<Player>
                {method} + init(ClientModelState) : void
                {method} + validate(ServerMessage) : void
                {method} + getClientCardState() : ClientCardState
                {method} [protected] getNext() : CardState
                {method} + progressTurn(Player) : void
                'ask why disconnect isn't here
            }

            CardState^--MeteorAnnounceState
            class MeteorAnnounceState {
                {field} [final] card_id : int
                {field} [final] left : ProjectileArray
                {field} [final] awaiting : List<Player>
                {field} broke_cabin : boolean
                {method} + init(ClientModelState) : void
                {method} + validate(ServerMessage) : void
                {method} + getClientCardState() : ClientCardState
                {method} [protected] getNext() : CardState
                {method} + turnOn(Player, ShipCoords, ShipCoords) : void
                {method} + progressTurn(Player) : void
                {method} + disconnect(Player) : void
            }

            CardState^--MeteorNewCabinState
            class MeteorNewCabinState {
                {field} [final] card_id : int
                {field} [final] left : ProjectileArray
                {method} + init(ClientModelState) : void
                {method} + validate(ServerMessage) : void
                {method} + getClientCardState() : ClientCardState
                {method} [protected] getNext() : CardState
                {method} + setNewShipCentre(Player, ShipCoords) : void
                {method} + disconnect(Player) : void
            }

            CardState^--OpenSpaceState
            class OpenSpaceState {
                {field} [final] card : OpenSpaceCard
                {field} [final] awaiting : List<Player>
                {method} + init(ClientModelState) : void
                {method} + validate(ServerMessage) : void
                {method} + getClientCardState() : ClientCardState
                {method} [protected] getNext() : CardState
                {method} + turnOn(Player, ShipCoords, ShipCoords) : void
                {method} + progressTurn(Player) : void
                {method} + disconnect(Player) : void
            }

            CardState^--PiratesAnnounceState
            class PiratesAnnounceState {
                {field} [final] card : PiratesCard
                {field} [final] list : List<Player>
                {field} responded : boolean
                {field} result : boolean
                {method} + init(ClientModelState) : void
                {method} + validate(ServerMessage) : void
                {method} + getClientCardState() : ClientCardState
                {method} [protected] getNext() : CardState
                {method} + turnOn(Player, ShipCoords, ShipCoords) : void
                {method} + progressTurn(Player) : void
                {method} + disconnect(Player) : void
            }

            CardState^--PiratesNewCabinState
            class PiratesNewCabinState {
                {field} [final] card : PiratesCard
                {field} [final] list : List<Player>
                {field} [final] shots : ProjectileArray
                {method} + init(ClientModelState) : void
                {method} + validate(ServerMessage) : void
                {method} + getClientCardState() : ClientCardState
                {method} [protected] getNext() : CardState
                {method} + setNewShipCentre(Player, ShipCoords) : void
                {metohd} + disconnect(Player) : void
            }

            CardState^--PiratesPenaltyState
            class PiratesPenaltyState {
                {field} [final] card : PiratesCard
                {field} [final] list : List<Player>
                {field} [final] shots : ProjectileArray
                {field} responded : boolean
                {method} + init(ClientModelState) : void
                {method} + validate(ServerMessage) : void
                {method} + getClientCardState() : ClientCardState
                {method} [protected] getNext() : CardState
                {method} + turnOn(Player, ShipCoords, ShipCoords) : void
                {method} + progressTurn(Player) : void
                {method} + disconnect(Player) : void
            }

            CardState^--PiratesRewardState
            class PiratesRewardState {
                {field} [final] card : PiratesCard
                {field} [final] list : List<Player>
                {field} responded : boolean
                {field} took_reward : boolean
                {method} + init(ClientModelState) : void
                {method} + validate(ServerMessage) : void
                {method} + getClientCardState() : ClientCardState
                {method} [protected] getNext() : CardState
                {method} + setTakeReward(Player, boolean) : void
                {method} + disconnect(Player) : void
            }

            CardState^--PlanetAnnounceState
            class PlanetAnnounceState {
                {field} [final] card : PlanetCard
                {field} [final] list : List<Player>
                {field} responded : boolean
                {field} id : int
                {method} + init(ClientModelState) : void
                {method} + validate(ServerMessage) : void
                {method} + getClientCardState() : ClientCardState
                {method} [protected] getNext() : CardState
                {method} + selectLanding(Player, int) : void
                {method} + disconnect(Player) : void
            }

            CardState^--PlanetRewardState
            class PlanetRewardState {
                {field} [final] card : PlanetCard
                {field} [final] list : List<Player>
                {field} [final] id : int
                {field} responded : boolean
                {method} + init(ClientModelState) : void
                {method} + validate(ServerMessage) : void
                {method} + getClientCardState() : ClientCardState
                {method} [protected] getNext() : CardState
                {method} + takeCargo(Player, ShipmentType, ShipCoords) : void
                {method} + moveCargo(Player, ShipmentType, ShipCoords, ShipCoords) : void
                {method} + discardCargo(Player, ShipmentType, ShipCoords) : void
                {method} + progressTurn(Player) : void
                {method} + disconnect(Player) : void
            }

            CardState^--SlaversAnnounceState
            class SlaversAnnounceState {
                {field} [final] card : SlaversCard
                {field} [final] list : List<Player>
                {field} responded : boolean
                {field} result : boolean
                {method} + init(ClientModelState) : void
                {method} + validate(ServerMessage) : void
                {method} + getClientCardState() : ClientCardState
                {method} [protected] getNext() : CardState
                {method} + turnOn(Player, ShipCoords, ShipCoords) : void
                {method} + progressTurn(Player) : void
                {method} + disconnect(Player) : void
            }

            CardState^--SlaversLoseState
            class SlaversLoseState {
                {field} [final] card : SlaversCard
                {field} [final] list : List<Player>
                {field} responded : boolean
                {field} coords : List<ShipCoords>
                {method} + init(ClientModelState) : void
                {method} + validate(ServerMessage) : void
                {method} + getClientCardState() : ClientCardState
                {method} [protected] getNext() : CardState
                {method} + removeCrew(Player, ShipCoords) : void
                {method} + disconnect(Player) : void
            }

            CardState^--SlaversRewardState
            class SlaversRewardState {
                {field} [final] card : SlaversCard
                {field} [final] list : List<Player>
                {field} responded : boolean
                {field} took_reward : boolean
                {method} + init(ClientModelState) : void
                {method} + validate(ServerMessage) : void
                {method} + getClientCardState() : ClientCardState
                {method} [protected] getNext() : CardState
                {method} + setTakeReward(Player, boolean) : void
                {method} + disconnect(Player) : void
            }

            CardState^--SmugglersAnnounceState
            class SmugglersAnnounceState {
                {field} [final] card : SmugglersCard
                {field} [final] list : List<Player>
                {field} responded : boolean
                {field} result : boolean
                {method} + init(ClientModelState) : void
                {method} + validate(ServerMessage) : void
                {method} + getClientCardState() : ClientCardState
                {method} [protected] getNext() : CardState
                {method} + turnOn(Player, ShipCoords, ShipCoords) : void
                {method} + progressTurn(Player) : void
                {method} + disconnect(player) : void
            }

            CardState^--SmugglersLoseState
            class SmugglersLoseState {
                {field} [final] card : SmugglersCard
                {field} [final] list : List<Player>
                {field} [final] required : int[]
                {field} responded : boolean
                {method} + init(ClientModelState) : void
                {method} + validate(ServerMessage) : void
                {method} + getClientCardState() : ClientCardState
                {method} [protected] getNext() : CardState
                {method} + discardCargo(Player, ShipmentType, ShipCoords) : void
                {method} + disconnect(Player) : void
            }

            CardState^--SmugglersRewardState
            class SmugglersRewardState {
                {field} [final] card : SmugglersCard
                {field} [final] list : List<Player>
                {field} responded : boolean
                {field} took_reward : boolean
                {method} + init(ClientModelState) : void
                {method} + validate(ServerMessage) : void
                {method} + getClientCardState() : ClientCardState
                {method} [protected] getNext() : CardState
                {method} + takeCargo(Player, ShipmentType, ShipCoords) : void
                {method} + moveCargo(Player, ShipmentType, ShipCoords, ShipCoords) : void
                {method} + discardCargo(Player, ShipmentType, ShipCoords) : void
                {method} + progressTurn(Player) : void
                {method} + disconnect(Player) : void
            }

            CardState^--StardustState
            class StardustState {
                {field} [final] card : StardustCard
                {field} awaiting : List<Player>
                {method} + init(ClientModelState) : void
                {method} + validate(ServerMessage) : void
                {method} + getClientCardState() : ClientCardState
                {method} [protected] getNext() : CardState
                {method} + progressTurn(Player) : void
            }
        }

        package Utils {

            class CombatZoneSection {
                {field} [final] criteria : CombatZoneCriteria
                {field} [final] penalty : CombatZonePenalty
                {field} [final] amount : int
                {method} + getCriteria)() : CombatZoneCriteria
                {method} + getPenalty() : CombatZonePenalty
                {method} + getAmount() : int
            }

            class Planet {
                {field} [final] contains : int[]
                {field} [final] visited : boolean
                {method} + getContains() : int[]
                {method} + visit() : void
                {method} + getVisited() : boolean
            }
            
            class Projectile {
                {field} [final] direction : ProjectileDirection
                {field} [final] dimension : ProjectileDimension
                {field} [final] offset : int
                {method} + getDirection() : ProjectileDirection
                {method} + getDimension() : PrjectileDimension
                {method} + getOffset() : int
            }         

            class ProjectileArray {
                {field} [field] projectiles : List<Projectile>
                {method} + getProjectiles : List<Projectile>
            }
                
        }

        package Visitors {
            
            class ContainsLoaderVisitor {
                {field} [final] cargo : ShipmentType
                {method} + visit(StorageComponent) : void
            }
            
            class ContainsRemoveVisitor {
                {field} [final] searching : shipmentType
                {method} + visit(StorageComponent) : void
                {method} + visit(BatteryCompoent) : void
            }

            class CrewRemoveVisitor {
                {field} [final] ship : SpaceShip
                {method} + visit(CabinComponent) : void
                {method} + visit(AlienLifeSupportComponent) : void
                {method} + visit(StartingCabinComponent) : void
            }

            class LargeMeteorVisitor {
                {field} d : ProjectileDirection
                {field} found_cannon : boolean
                {method} + visit(CannonComponent) : void
            }

        }

        interface iCard <<interface>> {
            {method} getId() : int
            {method} getDays() : int
            {method} getState(VoyageState) : CardState
            {method} getExhausted() : boolean
        }

        iCard^--Card
        abstract Card <<abstract>> {
            {field} id : int
            {field} days : int
            {field} exhausted : boolean
            {method} + getId() : int
            {method} + getDays() : int
            {method} + getExhausted() : boolean
            {method} [protected] exhaust() : void
        }

        Card^--AbandonedShipCard
        class AbandonedShipCard {
            {field} credits_gained : int
            {field} crew_lost : int
            {method} + getState(VoyageState) : CardState
            {method} + getCredits() : int
            {method} + getCrewLost() : int
            {method} + apply(VoyageState, Player, int) : void
        }

        Card^--AbandonedStationCard
        class AbandonedStationCard {
            {field} planet : Planet
            {field} crew : int
            {method} + getState(VoyageState) : CardState
            {method} + getPlanet() : Planet
            {method} + getCrewLost() : int
            {method} + apply(VoyageState, Player, int) : void
        }

        Card^--CombatZoneCard
        class CombatZoneCard {
            {field} sections : List<CombatZoneSection>
            {field} shots : ProjectileArray
            {method} + getState(VoyageState) : C
        }

        Card^--EpidemicCard
        class EpidemicCard {
            {method} + getState(VoyageState) : CardState
            {method} + apply(VoyageState, Player) : void
        }

        Card^--MeteorSwarmCard
        class MeteorSwarmCard {
            {field} meteorites : ProjectileArray
            {method} + getState(VoyageState) : CardState
            {method} + getMeteorites() : ProjectileArray
            {method} + apply(VoyageState, Projectile) : void
        }

        Card^--OpenSpaceCard
        class OpenSpaceCard {
            {method} + getState(VoyageState) : CardState
            {method} + apply(VoyageState, Player) : void
        }

        Card^--PiratesCard
        class PiratesCard {
            {field} [final] shots : ProjectileArray
            {field} [field] credits : int
            {field} [final] min_power : int
            {method} + getState(VoyageState) : CardState
            {method} + getCredits() : int
            {method} + getShots() : ProjectileArray
            {method} + apply(VoyageState, Player) : void
        }

        Card^--PlanetCard
        class PlanetCard {
            {field} [final] planets : List<Planet>
            {field} [final] left : int
            {method} + getState(VoyageState) : CardState
            {method} + getVisited() : List<boolean>
            {method} + getPlanet() : Planet
            {method} + getSize() : int
            {method} + apply(Player, int) : void
        }

        Card^--SlaversCard
        class SlaversCard {
            {field} [final] min_power : int
            {field} [final] crew_penalty : int
            {field} [final] credits : int
            {method} + getState(VoyageState) : CardState
            {method} + getCrewLost() : int
            {method} + getCredits() : int
            {method} + apply(VoyageState, Player) : void
        }

        Card^--SmugglersCard
        class SmugglersCard {
            {field} [final] reward : planet
            {field} [final] cargo_taken : int
            {field} [field] min_power : int
            {method} + getState(VoyageState) : CardState
            {method} + getReward() : Planet
            {method} + getCargoPenalty() : int
            {method} + apply(player) : void
        }

        Card^--StardustCard
        class StardustCard {
            {method} + getState(VoyageState) : CardState
            {method} + apply(VoyageState, Player) : void
        }
    }

    Components::Visitors::iVisitor .. ContainsLoaderVisitor
    Components::Visitors::iVisitor .. ContainsRemoveVisitor
    Components::Visitors::iVisitor .. CrewRemoveVisitor
    Components::Visitors::iVisitor .. LargeMeteorVisitor

    package Board {

        interface iCards <<interface>> {
            TODO
        }

        iCards^--Cards
        class Cards {
            TODO
        }

        interface iCommonBoard <<interface>> {
            TODO
        }

        iCommonBoard^..CommonBoard
        class CommonBoard {
            TODO
        }

        interface iPlanche <<interface>> {
            TODO
        }


        iPlanche^..Planche
        class Planche{
            TODO
        }

    }

    package Components {
        
        package Visitors {

            interface iVisitable <<interface>> {
                {method} + check(iVisitor) : void
            }

            interface iVisitor <<interface>> {
                {method} + visit(CabinComponent) : void
                {method} + visit(EngineComponent) : void
                {method} + visit(AlienLifeSupportComponent) : void
                {method} + visit(CannonComponent) : void
                {method} + visit(StorageComponent) : void
                {method} + visit(BatteryComponent) : void
                {method} + visit(ShieldComponent) : void
                {method} + visit(EmptyComponent) : void
                {method} + visit(StructuralComponent) : void
                {method} + visit(StartingCabinComponent) : void
            }

            iVisitor^..CabinVisitor
            class CabinVisitor {
                {field} type : AlienType
                {method} + getSupportedType() : AlienType
            }

            iVisitor^..EnergyVisitor
            class EnergyVisitor {
                TODO
            }

            iVisitor^..FreeSpaceVisitor
            class FreeSpaceVisitor {
                TODO
            }

            iVisitor^..SpaceShipUpdateVisitor
            class SpaceShipUpdateVisitor {
                TODO
            }
        
        }
        

        interface iBaseComponent <<interface>> {
            TODO
        }

        Visitors::iVisitable ^--BaseComponent
        iBaseComponent^--BaseComponent
        abstract BaseComponent <<abstract>> {
            TODO
        }

        BaseComponent^..AlienLifeSupportComponent
        class AlienLifeSupportComponent{
          
			{field} - type: AlienType
			{method} + check(iVisitor) : void
			{method} + getType() : AlienType
			{method} + onCreation(SpaceShip) : void
			{method} + onDelete(SpaceShip) : void
			{method} + getClientComponent() : ClientComponent
		}

        BaseComponent^..BatteryComponent
        class BatteryComponent {
			{field} - contains : int
			{field} - max : int
			{method} + check(iVisitor) : void
			{method} + getContains() : int
			{method} + getCapacity() : int
			{method} + takeOne() : void
			{method} + putOne() : void
			{method} + onCreation(SpaceShip) : void
			{method} + onDelete(SpaceShip) : void
			{method} + getClientComponent() : ClientComponent
		}

        BaseComponent^..CabinComponent
        class CabinComponent{
			{field} - crew_number : int
			{field} - crew_type : AlienType
		   	{method} + check(iVisitor) : void
			{method} + getCrew() : int
			{method} + getCrewType() : AlienType			
			{method} + setCrew(SpaceShip, int, AlienType) : void
			{method} + onCreation(SpaceShip) : void
			{method} + onDelete(SpaceShip) : void
			{method} + getClientComponent() : ClientComponent
		}

        BaseComponent^..StartingCabinComponent
        class StartingCabinComponent{
			{field} - color : PlayerColor
			{field} - crew_number : int
		   	{method} + check(iVisitor) : void
			{method} + getCrew() : int
			{method} + getCrewType() : AlienType		
			{method} + getColor() : PlayerColor
			{method} + setCrew(SpaceShip, int, AlienType)
			{method} + onCreation(SpaceShip) : void
			{method} + onDelete(SpaceShip) : void
			{method} + getClientComponent() : ClientComponent
		}

        BaseComponent^..CannonComponent
        class CannonComponent{			
			{field} - max_power : int
			{field} - powered : boolean
			{field} - powerable : boolean
			{method} + check(iVisitor) : void
			{method} + verify(SpaceShip) : boolean
			{method} + turnOn() : void
			{method} + turnOff() : void
			{method} + getCurrentPower() : int
			{method} + getPower() : int
			{method} + powerable() : boolean		
			{method} + onCreation(SpaceShip) : void
			{method} + onDelete(SpaceShip) : void
			{method} + getClientComponent() : ClientComponent
		}

        BaseComponent^..EmptyComponent
        class EmptyComponent{
			{method} + verify(SpaceShip) : boolean
			{method} + check(iVisitor) : void
			{method} + getConnectors() : ConnectorType[]
			{method} + onCreation(SpaceShip) : void
			{method} + onDelete(SpaceShip) : void
			{method} + getClientComponent() : ClientComponent
		}

        BaseComponent^..EngineComponent
        class EngineComponent{
			{field} - max_power : int
			{field} - powered : boolean
			{field} - powerable : boolean
			{method} + verify(SpaceShip) : boolean
			{method} + check(iVisitor) : void
			{method} + turnOn() : void
			{method} + turnOff() : void
			{method} + getCurrentPower() : int
			{method} + getPower() : int
			{method} + powerable() : boolean		
			{method} + onCreation(SpaceShip) : void
			{method} + onDelete(SpaceShip) : void
			{method} + getClientComponent() : ClientComponent
		}

        BaseComponent^..ShieldComponent
        class ShieldComponent{
			{field} - powered : boolean
			{method} + check(iVisitor) : void
			{method} + turnOn() : void
			{method} + turnOff() : void
			{method} + getPowered() : boolean
			{method} + powerable() : boolean	
			{method} + onCreation(SpaceShip) : void
			{method} + onDelete(SpaceShip) : void
			{method} + getShield() : ShieldType
			{method} + getClientComponent() : ClientComponent

		}
        
		BaseComponent^..StorageComponent
        class StorageComponent{
			{field} - [final] shipment : int []
			{field} - [final] type : StorageType
			{field} - currently_full : int
			{method} + putIn(ShipmentType) : void
			{method} + takeOut(ShipmentType) : boolean
			{method} + howMany(ShipmentType) : int
			{method} + getFreeSpaces() : int
			{method} + getSpecial() : boolean
			{method} + getCapacity() : int
			{method} + onCreation(SpaceShip) : void
			{method} + onDelete(SpaceShip) : void
			{method} + check(iVisitor) : void
			{method} + getClientComponent() : ClientComponent

		}
        BaseComponent^..StructuralComponent
        class StructuralComponent{
			{method} + check(iVisitor) : void
			{method} + onCreation(SpaceShip) : void
			{method} + onDelete(SpaceShip) : void
			{method} + getClientComponent() : ClientComponent
		}

    }

    package Player {
        
        interface SpaceShip <<interface>> {
            TODO
        }

        SpaceShip^..SpaceShip
        class SpaceShip {
            TODO
        }

        ShipCoords <-- "1" Components::BaseComponent
        class ShipCoords{
            TODO
        }

    }

    package State {
        
        abstract GameState <<abstract>> {
            {field} # [final] model : ModelInstance 
            {field} # [final] type : GameModeType
            {field} # [final] count : PlayerCount
            {field} # [final] players : List<Player>
            {method} + [abstract] validate(ServerMessage message) : void
            {method} + [abstract] getNext() : GameState 
            {method} + [abstract] getClientState() : ClientModelState 
            {method} + init() : void : void
            {method} + transition() : void : void
            {method} + getCount() : void : PlayerCount
            {method} + getPlayer(PlayerColor) : void : Player
            {method} + getType() : void : GameModeType
            {method} + connect(ClientDescriptor client) : void
            {method} + disconnect(ClientDescriptor client) : void
            {method} + connect(Player) : void
            {method} + disconnect(Player) : void
            {method} + sendContinue(Player) : void
            {method} + putComponent(Player, ShipCoords coords) : void
            {method} + takeComponent(Player) : void
            {method} + takeDiscarded(Player, int id) : void
            {method} + discardComponent(Player, int id) : void
            {method} + toggleHourglass(Player) : void
            {method} + removeComponent(Player, ShipCoords coords) : void
            {method} + setCrewType(Player, ShipCoords coords, AlienType type) : void
            {method} + giveUp(Player) : void
            {method} + CardState getCardState(Player) : void
        }

        GameState ^... WaitingState
        class WaitingState {
            {field} - [final] connected : List<ClientDescriptor>
            {field} - [final] count : PlayerCount
            {method} + validate(ServerMessage message) : void
            {method} + getNext() : GameState 
            {method} + getClientState() : ClientModelState 
            {method} + init() : void : void
            {method} + connect(ClientDescriptor client) : void
            {method} + disconnect(ClientDescriptor client) : void
        }

        GameState ^... ConstructionState
        class ConstructionState {
            {field} - [final] construction_cards : List<Integer> 
            {field} - [final] voyage_deck : iCards 
            {field} - [final] building : List<Player> 
            {field} - [final] finished : List<Player> 
            {field} - [final] hourglass : ConstructionStateHourglass 
            {field} - current_tile : HashMap<Player, iBaseComponent> 
            {field} - hoarded_tile : HashMap<Player, List<iBaseComponent>> 
            {method} + validate(ServerMessage message) : void
            {method} + getNext() : GameState 
            {method} + getClientState() : ClientModelState 
            {method} + init() : void : void
            {method} + connect(Player) : void
            {method} + disconnect(Player) : void
            {method} + sendContinue(Player) : void
            {method} + putComponent(Player, ShipCoords coords) : void
            {method} + takeComponent(Player) : void
            {method} + takeDiscarded(Player, int id) : void
            {method} + discardComponent(Player, int id) : void
            {method} + toggleHourglass(Player) : void
        }

        GameState ^... VerifyState
        class VerifyState {
            {field} - [final] voyage_deck : iCards 
            {field} - [final] to_validate : List<Player>
            {field} - [final] finish_order : List<Player>
            {method} + validate(ServerMessage message) : void
            {method} + getNext() : GameState 
            {method} + getClientState() : ClientModelState 
            {method} + init() : void : void
            {method} + connect(Player) : void
            {method} + disconnect(Player) : void
            {method} + sendContinue(Player) : void
            {method} + removeComponent(Player, ShipCoords coords) : void
            {method} + setCrewType(Player, ShipCoords coords, AlienType type) : void
        }

        GameState ^... VoyageState
        class VoyageState {
            {field} - [final] planche : iPlanche 
            {field} - [final] voyage_deck : iCards 
            {field} - [final] to_give_up : List<Player> 
            {field} - card : iCard 
            {field} - state : CardState state
            {method} + validate(ServerMessage message) : void
            {method} + getNext() : GameState 
            {method} + getClientState() : ClientModelState 
            {method} + init() : void : void
            {method} + connect(Player) : void
            {method} + disconnect(Player) : void
            {method} + giveUp(Player) : void
            {method} + getCardState(Player) : CardState
            {method} + loseGame(Player) : void
            {method} + getAllConnectedPlayers() : List<Player> 
            {method} + etOrder(CardOrder) : List<Player> 
            {method} + findCriteria(CombatZoneCriteria) : Player
            {method} + getPlanche() : iPlanche 
            {method} + setCardState(CardState) : void
        }

        GameState ^... EndscreenState
        class EndscreenState {
            {field} - [final] awaiting : List<Player> 
            {field} - [final] order_arrival : List<Player> 
            {method} + validate(ServerMessage message) : void
            {method} + getNext() : GameState 
            {method} + getClientState() : ClientModelState 
            {method} + init() : void : void
            {method} + sendContinue(Player) : void
            {method} + disconnect(Player) : void
        }
        
    }


    State::GameState "1" <-- ModelInstance:state 
    class ModelInstance {
        {field} - [final] controller : ServerController 
        {method} + validate(ServerMessage message) : void
        {method} + startGame(List<Player> players) : void
        {method} + getState() : GameState
        {method} + setState(GameState new_state) : void
        {method} + connect(ClientDescriptor client) : void
        {method} + disconnect(ClientDescriptor client) : void
        {method} + kick(ClientDescriptor client) : void
    }

    package Client {
        
        package Card {
            
            interface ClientCardState <<interface>> {
                {method} + showCardState(ClientView) : void
            }

            ClientCardState ^.. ClientBaseCardState
            class ClientBaseCardState {
                {field} - [final] id : int
                {method} + showCardState(ClientView) : void
            }

            ClientCardState ^.. ClassAwaitConfirmCardStateDecorator
            ClientBaseCardState <-- ClassAwaitConfirmCardStateDecorator:base
            class ClassAwaitConfirmCardStateDecorator {
                {field} - [final] awaiting : List<PlayerColor> 
                {method} + getAwaiting() : List<PlayerColor> 
                {method} + showCardState(ClientView) : void
            }

            ClientCardState ^.. ClientCargoPenaltyCardStateDecorator
            ClientBaseCardState <-- ClientCargoPenaltyCardStateDecorator:base
            class ClientCargoPenaltyCardStateDecorator {
                {field} - [final] turn : PlayerColor 
                {field} - [final] shipments : int[] 
                {method} + getTurn() : PlayerColor 
                {method} + getShipments() : int[] 
                {method} + showCardState(ClientView) : void
            }
            
            ClientCardState ^.. ClientCargoRewardCardStateDecorator
            ClientBaseCardState <-- ClientCargoRewardCardStateDecorator:base
            class ClientCargoRewardCardStateDecorator { 
                {field} - [final] turn : PlayerColor 
                {field} - [final] days_taken : int 
                {field} - [final] shipments : int[] 
                {method} + getTurn() : PlayerColor 
                {method} + getShipments() : int[] 
                {method} + showCardState(ClientView) : void
            } 
            
            ClientCardState ^.. ClientCombatZoneIndexCardStateDecorator
            ClientBaseCardState <-- ClientCombatZoneIndexCardStateDecorator:base
            class ClientCombatZoneIndexCardStateDecorator {
                {field} - [final] index : int 
                {method} + getIndex() : int
                {method} + showCardState(ClientView) : void
            }
            
            ClientCardState ^.. ClientCreditsRewardCardStateDecorator
            ClientBaseCardState <-- ClientCreditsRewardCardStateDecorator:base
            class ClientCreditsRewardCardStateDecorator {
                {field} - [final] turn : PlayerColor 
                {field} - [final] credits : int 
                {field} - [final] days_taken : int 
                {method} + getTurn() : PlayerColor
                {method} + getCredits() : int
                {method} + getDaysTaken() : int 
                {method} + showCardState(ClientView) : void
            }
            
            ClientCardState ^.. ClientCrewPenaltyCardStateDecorator
            ClientBaseCardState <-- ClientCrewPenaltyCardStateDecorator:base
            class ClientCrewPenaltyCardStateDecorator {
                {field} - [final] turn : PlayerColor 
                {field} - [final] days_taken : int 
                {method} + getTurn() : PlayerColor
                {method} + getDaysTaken() : int
                {method} + showCardState(ClientView) : void
            }
            
            ClientCardState ^.. ClientLandingCardStateDecorator
            ClientBaseCardState <-- ClientLandingCardStateDecorator:base
            class ClientLandingCardStateDecorator {
                {field} - [final] turn : PlayerColor 
                {field} - [final] days_taken : int 
                {field} - [final] crew_needed: int 
                {field} - [final] available : List<Boolean>
                {method} + getTurn() : PlayerColor
                {method} + getDaysTaken() : int
                {method} + getCrewNeeded() : int
                {method} + getAvailable() : List<Boolean>
                {method} + showCardState(ClientView) : void
            }
            
            ClientCardState ^.. ClientMeteoriteCardStateDecorator 
            ClientBaseCardState <-- ClientMeteoriteCardStateDecorator :base
            class ClientMeteoriteCardStateDecorator  {
                {field} - [final] meteorite : Projectile
                {method} + getProjectile() : Projectile
                {method} + showCardState(ClientView) : void
            }

            ClientCardState ^.. ClientNewCenterCardStateDecorator
            ClientBaseCardState <-- ClientNewCenterCardStateDecorator:base
            class ClientNewCenterCardStateDecorator {
                {field} - [final] awaiting : List<PlayerColor>
                {method} + getAwaiting() : List<PlayerColor>
                {method} + showCardState(ClientView) : void
            }
            
            ClientCardState ^.. ClientProjectileCardStateDecorator
            ClientBaseCardState <-- ClientProjectileCardStateDecorator:base
            class ClientProjectileCardStateDecorator {
                {field} - [final] shot : Projectile
                {method} + getProjectile() : Projectile
                {method} + showCardState(ClientView) : void
            }
        
        }
        
        package Components {
            
            interface ClientComponent <<interface>> {
                {method} + showComponent(ClientView) : void
            }

            ClientComponent ^.. ClientBaseComponent
            class ClientBaseComponent {
                {field} - [final] id : int
                {field} - [final] rotation : ComponentRotation
                {method} + getId() : int 
                {method} + getRotation() : ComponentRotation 
                {method} + showComponent(ClientView) : void
            }
            
            ClientComponent ^.. ClientBatteryComponentDecorator
            ClientBaseComponent <-- ClientBatteryComponentDecorator:base
            class ClientBatteryComponentDecorator {
                {field} - [final] batteries : int
                {method} + getBatteries() : int
                {method} + showComponent(ClientView) : void
            }

            ClientComponent ^.. ClientCrewComponentDecorator
            ClientBaseComponent <-- ClientCrewComponentDecorator:base
            class ClientCrewComponentDecorator {
                {field} - [final] type : AlienType 
                {field} - [final] crew : int
                {method} + getAlienType() : AlienType
                {method} + getCrew() : int
                {method} + showComponent(ClientView) : void
            }

            ClientComponent ^.. ClientPoweredComponentDecorator 
            ClientBaseComponent <-- ClientPoweredComponentDecorator:base
            class ClientPoweredComponentDecorator {
                {field} - [final] powered : boolean
                {method} + getPowered() : boolean
                {method} + showComponent(ClientView) : void
            }

            ClientComponent ^.. ClientShipmentComponentDecorator
            ClientBaseComponent <-- ClientShipmentComponentDecorator:base
            class ClientShipmentComponentDecorator {
                {field} - [final] shipments : int[]
                {method} + getShipments() : int[]
                {method} + showComponent(ClientView) : void
            }

            ClientComponent ^.. ClientBrokenVerifyComponentDecorator
            ClientBaseComponent <-- ClientBrokenVerifyComponentDecorator:base
            class ClientBrokenVerifyComponentDecorator {
                {method} + showComponent(ClientView) : void
            }

            class ClientSpaceShip {
                {field} - [final] type : GameModeType 
                {field} - [final] ship : ClientComponent[][] 
                {field} - [final] boolean[] shielded;
                {field} - [final] cannon_power : int
                {field} - [final] engine_power : int
                {field} - [final] energy_power : int
                {field} - [final] crew : int[]
                {method} + getType() : GameModeType
                {method} + getComponent(ShipCoords) : ClientComponent
                {method} + getShielded() : boolean[]
                {method} + getCannonPower() : int
                {method} + getEnginePower() : int
                {method} + getEnergyPower() : int
                {method} + getCrew() : int[]
            }

        }

        package Player {

            class ClientWaitingPlayer {
                {field} - [final] username : String
                {field} - [final] color : PlayerColor
                {method} + getUsername() : String
                {method} + getColor() : PlayerColor
            }
            
            ClientSpaceShip <-- ClientConstructionPlayer:ship
            class ClientConstructionPlayer {
                {field} - [final] username : String
                {field} - [final] color : PlayerColor
                {field} - [final] ship : ClientSpaceShip
                {field} - [final] reserved_components : List<Integer> 
                {field} - [final] boolean : finished
                {method} + getUsername() : String
                {method} + getColor() : PlayerColor
                {method} + getShip() : ClientSpaceShip
                {method} + getReserved() : List<Integer> 
                {method} + isFinished() : boolean
            }

            ClientSpaceShip <-- ClientVerifyPlayer:ship
            class ClientVerifyPlayer {
                {field} - [final] username : String
                {field} - [final] color : PlayerColor
                {field} - [final] ship : ClientSpaceShip
                {field} - [final] results : VerifyResult[][]
                {field} - [final] finished : boolean
                {field} - [final] order : int
                {method} + getUsername() : String
                {method} + getColor() : PlayerColor
                {method} + getShip() : ClientSpaceShip
                {method} + getResults() : VerifyResult[][] 
                {method} + isFinished() : boolean
                {method} + getOrder() : int
            }

            ClientSpaceShip <-- ClientVoyagePlayer:ship
            class ClientVoyagePlayer {
                {field} - [final] username : String
                {field} - [final] color : PlayerColor
                {field} - [final] ship : ClientSpaceShip
                {field} - [final] planche_slot : int
                {field} - [final] credits : int
                {field} - [final] disconnected : boolean
                {field} - [final] retired_lost : boolean
                {method} + getVerifyShip(VerifyResult[][]) : ClientSpaceShip
                {method} + getUsername() : String
                {method} + getColor() : PlayerColor
                {method} + getShip() : ClientSpaceShip
                {method} + getPlancheSlot() : int
                {method} + getCredits() : int
                {method} + getDisconnected() : boolean
                {method} + getRetired() : boolean
            }

            class ClientEndgamePlayer {
                {field} - [final] username : String
                {field} - [final] color : PlayerColor
                {field} - [final] planche_slot : int
                {field} - [final] credits : int
                {field} - [final] shipments : int[]
                {field} - [final] score : int
                {method} + getUsername() : String
                {method} + getColor() : PlayerColor
                {method} + getPlanche_slot() : int
                {method} + getCredits() : int
                {method} + getShipments() : int[]
                {method} + getScore() : int
            }

        }

        package State {
            
            interface ClientModelState <<interface>> {
                {method} + sendToView(ClientView) : void
            }

            ClientModelState ^.. ClientWaitingRoomState
            class ClientWaitingRoomState {
                {field} - [final] type : GameModeType
                {field} - [final] playerlist : List<ClientWaitingPlayer>
                {method} + getType() : GameModeType
                {method} + getPlayerList() : List<ClientWaitingPlayer>
                {method} + sendToView(ClientView) : void 
            }

            ClientModelState ^.. ClientConstructionState
            class ClientConstructionState {
                {field} - [final] type : GameModeType
                {field} - [final] playerlist : List<ClientConstructionPlayer> 
                {field} - [final] construction_cards : List<Integer> 
                {field} - [final] discarded_tiles : List<Integer> 
                {field} - [final] tiles_left : int
                {field} - [final] last_hourglass_toggle : Instant 
                {method} + getType() : GameModeType
                {method} + getPlayerList() : List<ClientConstructionPlayer> 
                {method} + getConstructionCards() : List<Integer> 
                {method} + getDiscardedTiles() : List<Integer> 
                {method} + getTilesLeft() : int
                {method} + getLastToggle() : Instant
                {method} + sendToView(ClientView) : void 
            }

            ClientModelState ^.. ClientVerifyState
            class ClientVerifyState {
                {field} - [final] players : List<ClientVerifyPlayer> 
                {method} + getPlayers() : List<ClientVerifyPlayer> 
                {method} + sendToView(ClientView) : void  
            }

            ClientModelState ^.. ClientVoyageState
            class ClientVoyageState {
                {field} - [final] type : GameModeType
                {field} - [final] playerlist : List<ClientVoyagePlayer> 
                {field} - [final] card_id : int
                {field} - [final] card_state : ClientCardState 
                {method} + getType() : GameModeType
                {method} + getPlayerList() : List<ClientVoyagePlayer> 
                {method} + getCardId() : int
                {method} + getCardState() : ClientCardState 
                {method} + sendToView(ClientView) : void 
            }

            ClientModelState ^.. ClientEndgameState
            class ClientEndgameState {
                {field} - [final] playerlist : List<ClientEndgamePlayer>
                {method} + getPlayerList() : List<ClientEndgamePlayer>
                {method} + sendToView(ClientView) : void 
            }

        }

    }
 
}


@enduml

'⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣤⣤⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
'⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⣿⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
'⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⣿⣿⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⣿⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀
'⠀⠀⠀⠀⠀⠀⠀⠀⣾⣿⣿⣿⣿⣿⣿⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⣿⣿⣿⣿⣿⣿⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀
'⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⣿⣿⣿⣿⣇⠀⠀⠀⠀⠀⠀⠀⢀⣿⣿⣿⣿⣿⣿⣿⣿⡆⠀⠀⠀⠀⠀⠀⠀⠀
'⠀⠀⠀⠀⠀⠀⢰⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡄⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⣿⣿⣿⣿⣷⠀⠀⠀⠀⠀⠀⠀⠀
'⠀⠀⠀⠀⠀⢀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⠀⠀⠀⠀⠀⢰⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀
'⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡄⠀⠀⠀⢀⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣇⠀⠀⠀⠀⠀⠀⠀
'⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀
'⠀⠀⠀⠀⢀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀
'⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀
'⠀⠀⠀⠀⠈⣿⣿⣿⣿⣿⣿⠟⠉⠀⠀⠀⠙⢿⣿⣿⣿⣿⣿⣿⣿⡿⠋⠀⠀⠙⢻⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀
'⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿⠃⠀⠀⠀⠀⣠⣄⠀⢻⣿⣿⣿⣿⣿⡿⠀⣠⣄⠀⠀⠀⢻⣿⣿⣏⠀⠀⠀⠀⠀⠀⠀
'⠀⠀⠀⠀⠀⣾⣿⣿⣿⣿⠀⠀⠀⠀⠰⣿⣿⠀⢸⣿⣿⣿⣿⣿⡇⠀⣿⣿⡇⠀⠀⢸⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀
'⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿⣄⠀⠀⠀⠀⠙⠃⠀⣼⣿⣿⣿⣿⣿⣇⠀⠙⠛⠁⠀⠀⣼⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀
'⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿⣿⣷⣤⣄⣀⣠⣤⣾⣿⣿⣿⣿⣽⣿⣿⣦⣄⣀⣀⣤⣾⣿⣿⣿⣿⠃⠀⠀⢀⣀⠀⠀
'⠰⡶⠶⠶⠶⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⠛⠉⠉⠙⠛⠋⠀
'⠀⠀⢀⣀⣠⣤⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠷⠶⠶⠶⢤⣤⣀⠀
'⠀⠛⠋⠉⠁⠀⣀⣴⡿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣯⣤⣀⡀⠀⠀⠀⠀⠘⠃
'⠀⠀⢀⣤⡶⠟⠉⠁⠀⠀⠉⠛⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠟⠉⠀⠀⠀⠉⠙⠳⠶⣄⡀⠀⠀
'⠀⠀⠙⠁⠀⠀⠀⠀⠀⠀⠀⠀⢰⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠁⠀⠀
'⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
'⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
'⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
'⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
'⠀⠀⠀⠀⠀⠀⠀⠀⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
'⠀⠀⠀⠀⠀⠀⠀⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
'⠀⠀⠀⠀⠀⠀⣰⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
'⠀⠀⠀⠀⠀⢰⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
'⠀⠀⠀⠀⢀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
'⠀⠀⠀⠀⣸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⠀⠀⠀